# Generated by Django 3.2.6 on 2021-08-28 03:57

import accounts.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Introduce tu correo electrónico', max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, help_text='Introduce tu nombre', max_length=150, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='Introduce tu apellido materno', max_length=150, verbose_name='Apellido Paterno')),
                ('last_name', models.CharField(blank=True, help_text='Introduce tu apellido paterno', max_length=150, verbose_name='Last Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, help_text='Imagen de usuario', null=True, upload_to=accounts.models.upload_to, verbose_name='Imágen')),
                ('street_address', models.CharField(blank=True, help_text='Ingrese la calle', max_length=250, verbose_name='Calle')),
                ('locality_address', models.CharField(blank=True, max_length=250, verbose_name='Localidad / Pueblo / Municipio')),
                ('zipcode_address', models.CharField(blank=True, help_text='Ingrese su código postal', max_length=10, verbose_name='Código postal')),
                ('city_address', models.CharField(blank=True, help_text='Ingrese la ciudad', max_length=100, verbose_name='Ciudad')),
                ('state_address', models.CharField(blank=True, help_text='Ingrese su estado', max_length=100, verbose_name='Estado')),
                ('country_address', models.CharField(blank=True, help_text='Ingrese país', max_length=100, verbose_name='País')),
                ('office_phone', models.CharField(blank=True, help_text='Ingrese teléfono', max_length=20, verbose_name='Teléfono de oficina')),
                ('mobile_phone', models.CharField(blank=True, help_text='Ingrese teléfono móvil', max_length=20, verbose_name='Teléfono móvil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
